version: '2'
services:
    www-data:
        container_name: www-data
        image:          centos:6.6
        command:        /bin/bash
        volumes:
                        - /Users/lilclimate/Public/workspace/meizu_company/data/etc:/data/etc
                        - /Users/lilclimate/Public/workspace/meizu_company/data/sh:/data/sh
                        - /Users/lilclimate/Public/workspace/meizu_company/data/opt:/data/opt
                        - /Users/lilclimate/Public/workspace/lua_demo:/data/openresty/nginx/lua
                        - /Users/lilclimate/Public/workspace/meizu_company/developer:/data/www
                        - /Users/lilclimate/Public/workspace:/data/www1
    redis:
            container_name: redis
            image: redis:3.2.1
            ports:
                        - "6379:6379"
    nginx-proxy:
            container_name: nginx-proxy
            build:          ./nginx1.11-proxy
            command:        service nginx start
            expose:
                            - 22
            ports:
                            - 80:80
                            - 443:443
            volumes_from:
                            - www-data
            depends_on:
                            # - nginx-php1
                            # - nginx-php2
                            - openresty-php1
                            - openresty-php2
            links:
                            # - nginx-php1:server1
                            # - nginx-php2:server2
                            - openresty-php1:server1
                            - openresty-php2:server2
            extra_hosts:
                            - i.flyme.cn:172.16.200.220
    openresty-1.11.2.1:
            container_name: openresty-1.11.2.1
            build:          ./openresty1.11.2.1
            command:        service nginx start
            ports:
                            - 8888:80
                            - 8080:8080
                            - 9090:9090
                            - 8083:8081
            volumes_from:
                            - www-data
            links:
                            - redis:redis
                            - mysql-master:mysql
            extra_hosts:
                            - cs-api.meizu.com:192.168.99.100
                            - zsk-api.meizu.com:192.168.99.100
    mysql-master:
            container_name: mysql-master
            image:          mysql:5.7.16
            privileged:     true
            ports:
                            - 3306:3306
            environment:
                            MYSQL_ROOT_PASSWORD: 123456
                            MYSQL_DATABASE: dbname
                            MYSQL_USER: user
                            MYSQL_PASSWORD: 123456
            volumes:
                        - /Users/lilclimate/Public/workspace/meizu_company/data/mysql_data:/var/lib/mysql
                        - /Users/lilclimate/Public/workspace/meizu_company/data/sh:/data/sh
            command:    /bin/sh /data/sh/run/mysql.sh
    # nodejs:
    #         container_name: nodejs
    #         build:          ./nodejs
    #         command:        /bin/sh /data/sh/run/nodejs.sh
    #         ports:
    #                         - 3001:3001
    #         volumes_from:
    #                         - www-data
    openresty-php1:
            container_name: openresty-php1
            build:          ./openresty-php5.6
            command:        /bin/sh /data/sh/run/nginx-php.sh
            privileged:     true
            ports:
                            - 8081:80
            volumes_from:
                            - www-data
            links:
                            - redis:redis
                            - mysql-master:mysql
            extra_hosts:
                            - zsk-api.meizu.com:192.168.99.100
                            - or-api.meizu.com:192.168.99.100
                            - zsk-manage.meizu.com:10.2.67.115
                            - i.flyme.cn:172.16.200.220
                            - mie.meizu.com:10.2.69.24
                            - uac.meizu.com:172.17.21.37
    openresty-php2:
            container_name: openresty-php2
            build:          ./openresty-php5.6
            command:        /bin/sh /data/sh/run/nginx-php.sh
            privileged:     true
            ports:
                            - 8082:80
            volumes_from:
                            - www-data
            links:
                            - redis:redis
                            - mysql-master:mysql
            extra_hosts:
                            - zsk-api.meizu.com:192.168.99.100
                            - or-api.meizu.com:192.168.99.100
                            - zsk-manage.meizu.com:10.2.67.115
                            - i.flyme.cn:172.16.200.220
                            - mie.meizu.com:10.2.69.24
                            - uac.meizu.com:172.17.21.37
    xunsearch:
            container_name: xunsearch
            build:          ./xunsearch1.4.10
            command:        /bin/sh /data/sh/run/xs.sh
            ports:
                            - 8383:8383
                            - 8384:8384
            volumes_from:
                            - www-data
